version: "3.9"
services:
    keycloak:
        depends_on: 
            - keycloak-db
        build:
            dockerfile: Dockerfile.keycloak
            context: .
        volumes:
            - ./realm.json:/tmp/primbaord-realm.json
        environment: 
            DB_VENDOR: POSTGRES
            DB_ADDR: keycloak-db
            DB_DATABASE: "${KEYCLOAK_POSTGRES_DB}"
            DB_USER: "${KEYCLOAK_POSTGRES_USER}"
            DB_SCHEMA: public
            DB_PASSWORD: "${KEYCLOAK_POSTGRES_PASSWORD}"
            PROXY_ADDRESS_FORWARDING: 'true'
            KEYCLOAK_USER: "${KEYCLOAK_USER}"
            KEYCLOAK_PASSWORD: "${KEYCLOAK_PASSWORD}"
            KEYCLOAK_IMPORT: /tmp/primboard-realm.json
    keycloak-db:
        image: postgres:13-alpine
        volumes:
            - primboard-keycloak-database-vol:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: "${KEYCLOAK_POSTGRES_DB}"
            POSTGRES_USER: "${KEYCLOAK_POSTGRES_USER}"
            POSTGRES_PASSWORD: "${KEYCLOAK_POSTGRES_PASSWORD}"
    nginx:
        image: nginx:1.19-alpine
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - primboard-nginx-vol:/etc/nginx/logs:rw
        environment: 
            - PROXY_ADDRESS_FORWARDING=true
        ports:
            - ${REVERSE_PROXY_PUBLIC_PORT}:80
    gateway:
        depends_on: 
            - keycloak
        image: mirisbowring/primboard-gateway:latest
        environment:
            - PORT=8765
            - MONGO_URL=mongodb://primboardapi:Start123@primboard-database:27017/primboard
            - DATABASE_NAME=primboard
            - HTTP=true
            - TLS_INSECURE=false
            - KEYCLOAK_URL=${HOST}/keycloak
            - KEYCLOAK_REALM=${KEYCLOAK_REALM}
            - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID_GATEWAY}
            - KEYCLOAK_SECRET=${KEYCLOAK_CLIENT_SECRET_GATEWAY}
            - ALLOWED_ORIGINS=${HOST}
            - TAG_PREVIEW_LIMIT=5
            - SESSION_ROTATION=false
            - DEFAULT_MEDIA_PAGE_SIZE=30
            - INVITE_VALIDITY=3
    node:
        depends_on:
            - gateway
        image: mirisbowring/primboard-node:latest
        environment:
            - BASEPATH=/data
            - TARGETPATH=/share
            - HTTP=true
            - GATEWAY_URL=https://${HOST}/gateway
            - KEYCLOAK_URL=https://${HOST}/keycloak
            - KEYCLOAK_REALM=primboard
            - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID_NODE}
            - KEYCLOAK_SECRET=${KEYCLOAK_CLIENT_SECRET_NODE}
            - PORT=8766
            - ALLOWED_ORIGINS=${HOST}
            - NODE_AUTH_ID=5f9eacd7e2c078a2988b9901
            - NODE_AUTH_SECRET=sdfnsdfjhsduifhsdiufhsdiuofhjsdi
        volumes:
            - primboard-node-vol:/data:rw
    primboard-database:
        image: mongo:4.4-bionic
        restart: unless-stopped
        environment: 
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
            MONGO_INITDB_DATABASE: admin
        volumes:
            - primboard-database-vol:/data/db
            - ./init.js:/docker-entrypoint-initdb.d/init.js:ro
    web:
        depends_on: 
            - keycloak
        image: mirisbowring/primboard-web:latest
        environment: 
            GATEWAY_URL: ${HOST}/gateway/
            KEYCLOAK_ISSUER: ${HOST}/keycloak/auth
            KEYCLOAK_REALM: ${KEYCLOAK_REALM}
            KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID_WEB}
        volumes:
            - primboard-web-vol:/etc/nginx/logs
volumes:
    primboard-database-vol:
    primboard-nginx-vol:
    primboard-node-vol:
    primboard-keycloak-database-vol:
    primboard-web-vol:
